const c=window.SOUL_CONFIG||{};if(!c.supabaseUrl||c.supabaseUrl.includes("COLE_"))document.body.innerHTML="<h2 style='padding:40px'>Configure primeiro o arquivo js/config.js com a URL e a publishable key do Supabase.</h2>";else{
const db=supabase.createClient(c.supabaseUrl,c.supabaseKey), bucket=c.storageBucket||"imagens", $=id=>document.getElementById(id), status=m=>$("status").textContent=m;
async function upload(file,folder){if(!file)return null;let ext=file.name.split(".").pop(),path=`site/${folder}/${crypto.randomUUID()}.${ext}`;let {error}=await db.storage.from(bucket).upload(path,file);if(error)throw error;return db.storage.from(bucket).getPublicUrl(path).data.publicUrl}
async function auth(){let {data}=await db.auth.getSession();show(!!data.session)}
function show(ok){$("login").hidden=ok;$("panel").hidden=!ok;if(ok){loadHome();loadAbout();listEvents();listTestimonials()}}
$("loginBtn").onclick=async()=>{let {error}=await db.auth.signInWithPassword({email:$("email").value,password:$("password").value});$("loginMsg").textContent=error?error.message:"";if(!error)show(true)}
$("logout").onclick=async()=>{await db.auth.signOut();show(false)}
document.querySelectorAll("aside [data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.hidden=true);$(b.dataset.tab).hidden=false})
async function loadHome(){let {data}=await db.from("home_content").select("*").eq("is_active",true).limit(1).maybeSingle();if(data){$("hTitle").value=data.title||"";$("hText").value=data.text||""}}
$("saveHome").onclick=async()=>{try{status("Salvando...");let media=await upload($("hMedia").files[0],"inicio"),{data:old}=await db.from("home_content").select("*").eq("is_active",true).limit(1).maybeSingle(),obj={title:$("hTitle").value,text:$("hText").value,is_active:true};if(media)obj.background_url=media;let q=old?db.from("home_content").update(obj).eq("id",old.id):db.from("home_content").insert(obj);let {error}=await q;if(error)throw error;status("Início salvo.")}catch(e){status(e.message)}}
async function loadAbout(){let {data}=await db.from("about_content").select("*").eq("is_active",true).limit(1).maybeSingle();if(data){$("aTitle").value=data.title||"";$("aText").value=data.text||""}}
$("saveAbout").onclick=async()=>{try{status("Salvando...");let {data:old}=await db.from("about_content").select("*").eq("is_active",true).limit(1).maybeSingle(),obj={title:$("aTitle").value,text:$("aText").value,is_active:true};for(let [id,key] of [["aLarge","photo_large_url"],["a1","photo_1_url"],["a2","photo_2_url"],["a3","photo_3_url"]]){let u=await upload($(id).files[0],"quem-somos");if(u)obj[key]=u}let q=old?db.from("about_content").update(obj).eq("id",old.id):db.from("about_content").insert(obj);let {error}=await q;if(error)throw error;status("Quem Somos salvo.")}catch(e){status(e.message)}}
async function ids(cat,sub){let {data:a}=await db.from("portfolio_categories").select("id").eq("name",cat).single();let {data:b}=await db.from("portfolio_subcategories").select("id").eq("category_id",a.id).eq("name",sub).single();return b.id}
$("addEvent").onclick=async()=>{try{status("Adicionando...");let sid=await ids($("eCat").value,$("eSub").value),{data:e,error}=await db.from("portfolio_events").insert({subcategory_id:sid,title:$("eTitle").value,description:$("eText").value}).select().single();if(error)throw error;if($("eYoutube").value)await db.from("portfolio_videos").insert({event_id:e.id,youtube_url:$("eYoutube").value});let fs=[...document.querySelectorAll(".eventPhoto")];for(let i=0;i<fs.length;i++){let u=await upload(fs[i].files[0],"galeria");if(u)await db.from("portfolio_images").insert({event_id:e.id,image_url:u,sort_order:i})}status("Evento adicionado.");listEvents()}catch(e){status(e.message)}}
async function listEvents(){let {data}=await db.from("portfolio_events").select("id,title,created_at").order("created_at",{ascending:false});$("eventList").innerHTML=(data||[]).map(x=>`<div class=item><span>${x.title}</span><button class=danger onclick="delEvent('${x.id}')">Excluir</button></div>`).join("")}
window.delEvent=async id=>{if(confirm("Excluir este evento?")){await db.from("portfolio_events").delete().eq("id",id);listEvents()}}
$("addTestimonial").onclick=async()=>{try{let f=$("tMedia").files[0],u=await upload(f,"depoimentos"),type=f&&f.type.startsWith("video")?"video":"photo";let {error}=await db.from("testimonials").insert({client_name:$("tName").value,testimonial_text:$("tText").value,media_type:type,media_url:u});if(error)throw error;status("Depoimento adicionado.");listTestimonials()}catch(e){status(e.message)}}
async function listTestimonials(){let {data}=await db.from("testimonials").select("id,client_name").order("created_at",{ascending:false});$("testimonialList").innerHTML=(data||[]).map(x=>`<div class=item><span>${x.client_name||"Sem nome"}</span><button class=danger onclick="delT('${x.id}')">Excluir</button></div>`).join("")}
window.delT=async id=>{if(confirm("Excluir este depoimento?")){await db.from("testimonials").delete().eq("id",id);listTestimonials()}}
auth();}
